# Generated by Django 6.0.6 on 2026-06-22 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modifier', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField(default=1)),
                ('price_buy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
